# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build under C++20 or later
  build-clang-cpp20:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build
        run: clang++ -O3 --std=c++20 -Wall -Wextra -I./include test/test.cpp -o test-clang-20

      # Runs a set of commands using the runners shell
      - name: Test
        run: ./test-clang-20
