#
# Run Clang Tidy to verify code
#

name: Clang Tidy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-clang-cpp17:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Clang Tidy Check
        run: clang-tidy -header-filter=".*" test/test.cpp -- -I./include --std=c++17
